<template>
  <component :is="iconComponent" v-if="iconComponent" v-bind="$attrs" />
</template>

<script setup>
import { computed, defineAsyncComponent } from 'vue'

defineOptions({ inheritAttrs: false })

const props = defineProps({
  name: {
    type: String,
    required: true,
  },
})

const iconMap = {
  'activity': () => import('./ActivityIcon.vue'),
  'address': () => import('./AddressIcon.vue'),
  'apps': () => import('./AppsIcon.vue'),
  'arrow-up-right': () => import('./ArrowUpRightIcon.vue'),
  'ascending': () => import('./AscendingIcon.vue'),
  'attachment': () => import('./AttachmentIcon.vue'),
  'avatar': () => import('./AvatarIcon.vue'),
  'bell': () => import('./BellIcon.vue'),
  'calendar': () => import('./CalendarIcon.vue'),
  'camera': () => import('./CameraIcon.vue'),
  'certificate': () => import('./CertificateIcon.vue'),
  'check-circle': () => import('./CheckCircleIcon.vue'),
  'check': () => import('./CheckIcon.vue'),
  'collapse-sidebar': () => import('./CollapseSidebar.vue'),
  'columns': () => import('./ColumnsIcon.vue'),
  'comment': () => import('./CommentIcon.vue'),
  'contact': () => import('./ContactIcon.vue'),
  'contacts': () => import('./ContactsIcon.vue'),
  'convert': () => import('./ConvertIcon.vue'),
  'crm-logo': () => import('./CRMLogo.vue'),
  'dashboard': () => import('./DashboardIcon.vue'),
  'deals': () => import('./DealsIcon.vue'),
  'declined-call': () => import('./DeclinedCallIcon.vue'),
  'description': () => import('./DescriptionIcon.vue'),
  'desending': () => import('./DesendingIcon.vue'),
  'details': () => import('./DetailsIcon.vue'),
  'dialpad': () => import('./DialpadIcon.vue'),
  'document': () => import('./DocumentIcon.vue'),
  'dot': () => import('./DotIcon.vue'),
  'double-check': () => import('./DoubleCheckIcon.vue'),
  'drag': () => import('./DragIcon.vue'),
  'drag-vertical': () => import('./DragVerticalIcon.vue'),
  'duplicate': () => import('./DuplicateIcon.vue'),
  'duration': () => import('./DurationIcon.vue'),
  'edit': () => import('./EditIcon.vue'),
  'email2': () => import('./Email2Icon.vue'),
  'email-at': () => import('./EmailAtIcon.vue'),
  'email': () => import('./EmailIcon.vue'),
  'email-template': () => import('./EmailTemplateIcon.vue'),
  'erp-next': () => import('./ERPNextIcon.vue'),
  'event': () => import('./EventIcon.vue'),
  'export': () => import('./ExportIcon.vue'),
  'external-link': () => import('./ExternalLinkIcon.vue'),
  'facebook': () => import('./FacebookIcon.vue'),
  'file-audio': () => import('./FileAudioIcon.vue'),
  'file': () => import('./FileIcon.vue'),
  'file-image': () => import('./FileImageIcon.vue'),
  'file-spreadsheet': () => import('./FileSpreadsheetIcon.vue'),
  'file-text': () => import('./FileTextIcon.vue'),
  'file-type': () => import('./FileTypeIcon.vue'),
  'file-video': () => import('./FileVideoIcon.vue'),
  'filter': () => import('./FilterIcon.vue'),
  'frappe-cloud': () => import('./FrappeCloudIcon.vue'),
  'gender': () => import('./GenderIcon.vue'),
  'google': () => import('./GoogleIcon.vue'),
  'group-by': () => import('./GroupByIcon.vue'),
  'heart': () => import('./HeartIcon.vue'),
  'help': () => import('./HelpIcon.vue'),
  'inbound-call': () => import('./InboundCallIcon.vue'),
  'inbox': () => import('./InboxIcon.vue'),
  'indicator': () => import('./IndicatorIcon.vue'),
  'invite': () => import('./InviteIcon.vue'),
  'kanban': () => import('./KanbanIcon.vue'),
  'leads': () => import('./LeadsIcon.vue'),
  'lightning': () => import('./LightningIcon.vue'),
  'link': () => import('./LinkIcon.vue'),
  'list': () => import('./ListIcon.vue'),
  'loading-indicator': () => import('./LoadingIndicator.vue'),
  'location': () => import('./LocationIcon.vue'),
  'map': () => import('./MapIcon.vue'),
  'mark-as-done': () => import('./MarkAsDoneIcon.vue'),
  'maximize': () => import('./MaximizeIcon.vue'),
  'menu': () => import('./MenuIcon.vue'),
  'minimize': () => import('./MinimizeIcon.vue'),
  'missed-call': () => import('./MissedCallIcon.vue'),
  'money': () => import('./MoneyIcon.vue'),
  'mute': () => import('./MuteIcon.vue'),
  'note': () => import('./NoteIcon.vue'),
  'notifications': () => import('./NotificationsIcon.vue'),
  'organizations': () => import('./OrganizationsIcon.vue'),
  'outbound-call': () => import('./OutboundCallIcon.vue'),
  'pause': () => import('./PauseIcon.vue'),
  'people': () => import('./PeopleIcon.vue'),
  'phone': () => import('./PhoneIcon.vue'),
  'pin': () => import('./PinIcon.vue'),
  'playback-speed': () => import('./PlaybackSpeedIcon.vue'),
  'play': () => import('./PlayIcon.vue'),
  'quick-filter': () => import('./QuickFilterIcon.vue'),
  'react': () => import('./ReactIcon.vue'),
  'refresh': () => import('./RefreshIcon.vue'),
  'reload': () => import('./ReloadIcon.vue'),
  'reply-all': () => import('./ReplyAllIcon.vue'),
  'reply': () => import('./ReplyIcon.vue'),
  'right-side-layout': () => import('./RightSideLayoutIcon.vue'),
  'select': () => import('./SelectIcon.vue'),
  'settings': () => import('./SettingsIcon.vue'),
  'settings2': () => import('./SettingsIcon2.vue'),
  'shield': () => import('./ShieldIcon.vue'),
  'sliders': () => import('./SlidersIcon.vue'),
  'smile': () => import('./SmileIcon.vue'),
  'sort': () => import('./SortIcon.vue'),
  'sparkle': () => import('./SparkleIcon.vue'),
  'square-asterisk': () => import('./SquareAsterisk.vue'),
  'steps': () => import('./StepsIcon.vue'),
  'success': () => import('./SuccessIcon.vue'),
  'task': () => import('./TaskIcon.vue'),
  'task-priority': () => import('./TaskPriorityIcon.vue'),
  'task-status': () => import('./TaskStatusIcon.vue'),
  'telegram': () => import('./TelegramIcon.vue'),
  'territory': () => import('./TerritoryIcon.vue'),
  'unpin': () => import('./UnpinIcon.vue'),
  'volumn-high': () => import('./VolumnHighIcon.vue'),
  'volumn-low': () => import('./VolumnLowIcon.vue'),
  'website': () => import('./WebsiteIcon.vue'),
  'whats-app': () => import('./WhatsAppIcon.vue'),
}

const asyncComponentCache = {}

function getAsyncIcon(name) {
  if (!asyncComponentCache[name]) {
    const loader = iconMap[name]
    asyncComponentCache[name] = loader ? defineAsyncComponent(loader) : null
  }
  return asyncComponentCache[name]
}

const iconComponent = computed(() => getAsyncIcon(props.name))
</script>
