// All 32 Finance Cockpit report definitions.
// __COMPANY__ is substituted at click-time with the active company.

/** @type {Array<{label:string, report:string, group:string, defaultFilters:Record<string,string>, roles:string[], source:string}>} */
export const REPORTS = [
  // --- AR ---
  {
    label: 'Accounts Receivable',
    report: 'Accounts Receivable',
    group: 'AR',
    defaultFilters: { company: '__COMPANY__', report_date: '__TODAY__' },
    roles: ['Finance Manager', 'AR Accountant'],
    source: 'erpnext',
  },
  {
    label: 'Accounts Receivable Summary',
    report: 'Accounts Receivable Summary',
    group: 'AR',
    defaultFilters: { company: '__COMPANY__' },
    roles: ['Finance Manager', 'AR Accountant'],
    source: 'erpnext',
  },
  {
    label: 'Sales Invoice Trends',
    report: 'Sales Invoice Trends',
    group: 'AR',
    defaultFilters: { company: '__COMPANY__' },
    roles: ['Finance Manager', 'AR Accountant'],
    source: 'erpnext',
  },
  {
    label: 'Customer Credit Balance',
    report: 'Customer Credit Balance',
    group: 'AR',
    defaultFilters: { company: '__COMPANY__' },
    roles: ['Finance Manager', 'AR Accountant'],
    source: 'erpnext',
  },
  {
    label: 'Sales Payment Summary',
    report: 'Sales Payment Summary',
    group: 'AR',
    defaultFilters: { company: '__COMPANY__' },
    roles: ['Finance Manager', 'AR Accountant'],
    source: 'erpnext',
  },
  {
    label: 'Item-wise Sales Register',
    report: 'Item-wise Sales Register',
    group: 'AR',
    defaultFilters: { company: '__COMPANY__' },
    roles: ['Finance Manager', 'AR Accountant'],
    source: 'erpnext',
  },
  // --- AP ---
  {
    label: 'Accounts Payable',
    report: 'Accounts Payable',
    group: 'AP',
    defaultFilters: { company: '__COMPANY__', report_date: '__TODAY__' },
    roles: ['Finance Manager', 'AP Accountant'],
    source: 'erpnext',
  },
  {
    label: 'Accounts Payable Summary',
    report: 'Accounts Payable Summary',
    group: 'AP',
    defaultFilters: { company: '__COMPANY__' },
    roles: ['Finance Manager', 'AP Accountant'],
    source: 'erpnext',
  },
  {
    label: 'Purchase Invoice Trends',
    report: 'Purchase Invoice Trends',
    group: 'AP',
    defaultFilters: { company: '__COMPANY__' },
    roles: ['Finance Manager', 'AP Accountant'],
    source: 'erpnext',
  },
  {
    label: 'Supplier Credit Balance',
    report: 'Supplier Credit Balance',
    group: 'AP',
    defaultFilters: { company: '__COMPANY__' },
    roles: ['Finance Manager', 'AP Accountant'],
    source: 'erpnext',
  },
  {
    label: 'Purchase Payment Summary',
    report: 'Purchase Payment Summary',
    group: 'AP',
    defaultFilters: { company: '__COMPANY__' },
    roles: ['Finance Manager', 'AP Accountant'],
    source: 'erpnext',
  },
  {
    label: 'Item-wise Purchase Register',
    report: 'Item-wise Purchase Register',
    group: 'AP',
    defaultFilters: { company: '__COMPANY__' },
    roles: ['Finance Manager', 'AP Accountant'],
    source: 'erpnext',
  },
  // --- P&L ---
  {
    label: 'Profit and Loss Statement',
    report: 'Profit and Loss Statement',
    group: 'PL',
    defaultFilters: { company: '__COMPANY__' },
    roles: ['Finance Manager'],
    source: 'erpnext',
  },
  {
    label: 'Balance Sheet',
    report: 'Balance Sheet',
    group: 'PL',
    defaultFilters: { company: '__COMPANY__' },
    roles: ['Finance Manager'],
    source: 'erpnext',
  },
  {
    label: 'Cash Flow Statement',
    report: 'Cash Flow',
    group: 'PL',
    defaultFilters: { company: '__COMPANY__' },
    roles: ['Finance Manager'],
    source: 'erpnext',
  },
  {
    label: 'Consolidated Financial Statements',
    report: 'Consolidated Financial Statement',
    group: 'PL',
    defaultFilters: { company: '__COMPANY__' },
    roles: ['Finance Manager'],
    source: 'erpnext',
  },
  {
    label: 'Deferred Revenue and Expense',
    report: 'Deferred Revenue and Expense',
    group: 'PL',
    defaultFilters: { company: '__COMPANY__' },
    roles: ['Finance Manager'],
    source: 'erpnext',
  },
  // --- GL ---
  {
    label: 'General Ledger',
    report: 'General Ledger',
    group: 'GL',
    defaultFilters: { company: '__COMPANY__' },
    roles: ['Finance Manager'],
    source: 'erpnext',
  },
  {
    label: 'Trial Balance',
    report: 'Trial Balance',
    group: 'GL',
    defaultFilters: { company: '__COMPANY__' },
    roles: ['Finance Manager'],
    source: 'erpnext',
  },
  {
    label: 'Trial Balance for Party',
    report: 'Trial Balance for Party',
    group: 'GL',
    defaultFilters: { company: '__COMPANY__' },
    roles: ['Finance Manager'],
    source: 'erpnext',
  },
  {
    label: 'Bank Reconciliation Statement',
    report: 'Bank Reconciliation Statement',
    group: 'GL',
    defaultFilters: { company: '__COMPANY__' },
    roles: ['Finance Manager', 'AR Accountant', 'AP Accountant'],
    source: 'erpnext',
  },
  {
    label: 'Payment Period Based On Invoice Date',
    report: 'Payment Period Based On Invoice Date',
    group: 'GL',
    defaultFilters: { company: '__COMPANY__' },
    roles: ['Finance Manager'],
    source: 'erpnext',
  },
  // --- Assets ---
  {
    label: 'Asset Register',
    report: 'Asset Register',
    group: 'Assets',
    defaultFilters: { company: '__COMPANY__' },
    roles: ['Finance Manager'],
    source: 'erpnext',
  },
  {
    label: 'Fixed Asset Register',
    report: 'Fixed Asset Register',
    group: 'Assets',
    defaultFilters: { company: '__COMPANY__' },
    roles: ['Finance Manager'],
    source: 'erpnext',
  },
  {
    label: 'Asset Depreciation Ledger',
    report: 'Asset Depreciation Ledger',
    group: 'Assets',
    defaultFilters: { company: '__COMPANY__' },
    roles: ['Finance Manager'],
    source: 'erpnext',
  },
  {
    label: 'Asset Movement',
    report: 'Asset Movement',
    group: 'Assets',
    defaultFilters: { company: '__COMPANY__' },
    roles: ['Finance Manager'],
    source: 'erpnext',
  },
  // --- Partner ---
  {
    label: 'Rebate Voucher Register',
    report: 'CRM Partner Rebate Register',
    group: 'Partner',
    defaultFilters: { company: '__COMPANY__' },
    roles: ['Finance Manager', 'AR Accountant', 'Partner RM'],
    source: 'crm',
  },
  {
    label: 'Sales Commission Register',
    report: 'CRM Sales Commission Register',
    group: 'Partner',
    defaultFilters: { company: '__COMPANY__' },
    roles: ['Finance Manager', 'AR Accountant', 'Sales Manager'],
    source: 'crm',
  },
  {
    label: 'Partner Performance Summary',
    report: 'CRM Partner Performance',
    group: 'Partner',
    defaultFilters: { company: '__COMPANY__' },
    roles: ['Finance Manager', 'AR Accountant'],
    source: 'crm',
  },
  {
    label: 'Commission Payout Summary',
    report: 'CRM Commission Payout',
    group: 'Partner',
    defaultFilters: { company: '__COMPANY__' },
    roles: ['Finance Manager', 'Sales Manager'],
    source: 'crm',
  },
  {
    label: 'Rebate Liability Ageing',
    report: 'CRM Rebate Liability Ageing',
    group: 'Partner',
    defaultFilters: { company: '__COMPANY__' },
    roles: ['Finance Manager', 'AR Accountant'],
    source: 'crm',
  },
  {
    label: 'Deal Revenue Attribution',
    report: 'CRM Deal Revenue Attribution',
    group: 'Partner',
    defaultFilters: { company: '__COMPANY__' },
    roles: ['Finance Manager', 'AR Accountant', 'Sales Manager', 'Partner RM'],
    source: 'crm',
  },
]

export const GROUPS = ['AR', 'AP', 'PL', 'GL', 'Assets', 'Partner']

export const GROUP_LABELS = {
  AR: 'Accounts Receivable',
  AP: 'Accounts Payable',
  PL: 'P&L / Balance Sheet',
  GL: 'General Ledger',
  Assets: 'Assets',
  Partner: 'Partner & Commission',
}
